export enum Colors {
  INFO = 'border: 3px dotted; background-color: lightblue; padding: 5px',
  INFO_2 = 'border: 3px dotted; background-color: yellow; padding: 5px',
  INFO_FIN = 'border: 3px dotted; background-color: yellowgreen; padding: 5px',
  RED = 'border: 3px dotted red',
  BIG_RED = 'border: 5px dotted red; background-color: red; color: white',
  BIG_BLUE = 'border: 5px dotted dodgerblue; background-color: lightblue; padding: 5px',
  BIGBIG_BLUE = 'border: 5px dotted black; background-color: lightblue; padding: 10px',
  BIGBIG_GREEN = 'border: 5px dotted dodgerblue; background-color: yellowgreen; color: white; padding: 10px',
  BIGBIG_RED = 'border: 5px dotted dodgerblue; background-color: red; color: white; padding: 10px',
  BIG_YELLOW = 'border: 3px dotted red; background-color: yellow; padding: 5px',
  BIG_ORANGE = 'border: 5px dotted orangered; background-color: yellow; padding: 5px',
  BIG_MAG = 'border: 5px dotted black; background-color: magenta; padding: 5px',
  BIG_GREY = 'border: 3px dotted black; background-color: grey; padding: 5px',
  GOLD = 'border: 5px dotted gold; background-color: grey; padding: 5px',
  GOLDEN = 'border: 7px dashed red; background-color: beige; padding: 5px',
  GOLDEN_RED = 'border: 7px dotted red; background-color: beige; padding: 5px',
  GOLDEN_BLACK = 'border: 7px dotted black; background-color: beige; padding: 5px',
}
